Updated windows script for infra 19 (#103)
* Updated windows script for infra 19

Signed-off-by: vviveksharma <visharma@progress.com>

* Added fix

Signed-off-by: vviveksharma <visharma@progress.com>

* Added review comments

Signed-off-by: vviveksharma <visharma@progress.com>

* Added the filename changes

Signed-off-by: vviveksharma <visharma@progress.com>

* Added fixes for the script

Signed-off-by: vviveksharma <visharma@progress.com>

* Updated the invode request

Signed-off-by: vviveksharma <visharma@progress.com>

* Updated the product name

Signed-off-by: vviveksharma <visharma@progress.com>

* Updated error message

Signed-off-by: vviveksharma <visharma@progress.com>

* Added the if block

Signed-off-by: vviveksharma <visharma@progress.com>

---------

Signed-off-by: vviveksharma <visharma@progress.com>

diff --git a/templates/install.sh.tmpl b/templates/install.sh.tmpl
--- a/templates/install.sh.tmpl
+++ b/templates/install.sh.tmpl
@@ -617,8 +617,6 @@ determine_package_type() {
       echo "rpm"
       ;;
     "sles"|"opensuseleap")
-      $platform="linux"
-      $platform_version="pm"
       echo "rpm"
       ;;
     "aix")
@@ -638,6 +636,11 @@ determine_package_type() {
   esac
 }
 
+if [ "$package_manager" = "tar" ]; then
+  echo "Error: Script generation is not supported package_manager 'tar'."
+  exit 1
+fi
+
 # Ensure the package_manager field is correctly set based on the -i flag or dynamically determined.
 if [ "$project" = "chef-ice" ]; then 
   if [ -z "$package_manager" ]; then
@@ -653,8 +656,8 @@ else
   package_manager="pm"
 fi
 
-if [ "$project" = "migration-tools" ]; then
-  echo "Error: Script generation is not supported for the product 'migration-tools'."
+if [ "$project" = "migrate-ice" ]; then
+  echo "Error: Script generation is not supported for the product 'migrate-ice'."
   exit 1
 fi
 
