Updated error message
Signed-off-by: vviveksharma <visharma@progress.com>

diff --git a/templates/install.sh.tmpl b/templates/install.sh.tmpl
--- a/templates/install.sh.tmpl
+++ b/templates/install.sh.tmpl
@@ -617,8 +617,6 @@ determine_package_type() {
       echo "rpm"
       ;;
     "sles"|"opensuseleap")
-      $platform="linux"
-      $platform_version="pm"
       echo "rpm"
       ;;
     "aix")
@@ -637,6 +635,11 @@ determine_package_type() {
       ;;
   esac
 }
+
+if test "$package_manager" = "tar"; then
+  echo "Error: Script generation is not supported package_manager 'tar'."
+  exit 1
+fi
 
 # Ensure the package_manager field is correctly set based on the -i flag or dynamically determined.
 if [ "$project" = "chef-ice" ]; then 
